### ISSUE TITLE
[BUG] Distribution acronym is confusing

### ISSUE THREAD

**Issue by asquelt** [EuroLinux/eurolinux-distro-bugs#1]
**Describe the bug**
EuroLinux uses EL as an acronym for distribution, which collides with Enterprise Linux (EL).

**System version and platform**
ALL

**To Reproduce**

Steps to reproduce the behaviour:
```
[root@localhost ~]# rpm -qa --queryformat="%{release}\n"|sed -e 's/.*\.//'|sort|uniq -c|sort -nr
    412 el8
     36 1
     33 el8_4
     14 2
     11 0+3455+3ddf2832
      9 el8_3
      1 el8_2
      1 el8_1
      1 5e26cb2e
      1 3
```

**Expected behaviour**
As EU is common acronym for Europe (see .eu TLD) it would be intuitive to use EUL as EuroLinux acronym.

**Additional context**
NA

**Comment by AlexBaranowski** [comment]
Hi Andy,

First of all - thanks for your feedback.

*This is not the bug. It's a feature.** 

We are the only RHEL clone distro that keeps releases **same** even with modular packages. It's a feature that allows security software that scans the system by running queries on RPMs to work correctly on EuroLinux when configured for RHEL.

The next and separate topic: Red Hat uses `el8` disttag, EPEL uses this disttag, and new RHEL clones also use it. By changing the disttag to something different, we will break compatibility.
