### ISSUE TITLE
[BUG] EuroLinux claims DISA STIG support

### ISSUE THREAD

**Issue by squinky86** [EuroLinux/eurolinux-distro-bugs#2]
**Describe the bug**
EuroLinux installer (8.5) claims that there is a DISA EuroLinux STIG (V1R3). DISA has not released a STIG for EuroLinux. The language should probably mention that it's using the DISA RHEL STIG so that users are not confused into thinking that DISA has released a STIG for EuroLinux.

**System version and platform**
8.5, x86_64

**To Reproduce**
Select the DISA STIG security profile during installation

**Expected behaviour**
The text should be applying the DISA RHEL STIG (language should probably be changed for the CIS profiles as well).

![euro](https://user-images.githubusercontent.com/24464454/163003512-34dd7b97-2114-4e87-a6e3-fbba6b7afb21.png)

**Comment by AlexBaranowski** [comment]
@squinky86, thanks for the report. We should change the string to be cleaner. And it will be good time to do so as 8.6 is coming :).

Could you propose how to describe it the best? I though about something like:

- DIST STIG for RHEL 8 adapted for EuroLinux 8

**Comment by AlexBaranowski** [comment]
@tompods what do You think?

**Comment by squinky86** [comment]
> @squinky86, thanks for the report. We should change the string to be cleaner. And it will be good time to do so as 8.6 is coming :).
> 
> Could you propose how to describe it the best? I though about something like:
> 
> * DIST STIG for RHEL 8 adapted for EuroLinux 8

This makes sense to me and solves any confusion the user may have about DISA approvals. Good choice!
I'd also recommend similar wording for the CIS profiles.

**Comment by ghost** [comment]
@squinky86, thank you!
An EL8.6 GA ISO will have a less confusing description. We'll notify you once the change is adapted.

**Comment by AlexBaranowski** [comment]
@squinky86, as promised, we fixed it in the EuroLinux 8.6 with your suggestions.

![github-close](https://user-images.githubusercontent.com/8447941/167967908-8345b4ce-0de0-49f6-9a6e-c03f2c10f79b.png)

As You suggested, CIS profiles are also marked that way 😸 .

I'm currently pushing ISOs, so You can test it yourself in about 2 hours.

I want to thank You from the very bottom of my soul.

Best,
Alex
