### ISSUE TITLE
Eurolinux 9.0 installation error

### ISSUE THREAD

**Issue by mathewal** [EuroLinux/eurolinux-distro-bugs#6]
I am unable to install Eurolinux 9.0.

Every time I attempt booting from the USB, it ends up with a blue screen with the message "ERROR Verification Failed: (0 x 1A) Security Violation" displayed and an OK "button".

The USB was created using the Eurolinux 9.0 ISO file downloaded from Euro-Linux website.

There were no errors in writing the ISO to the USB.

Motherboard is Gigabyte Z590UD with 11th Gen Intel Core i9-11900 processor and 32 GiB of memory (Corsair).

Any suggestions please - How to make the USB boot into Eurolinux 9.0?

I am a non-tech user wanting to try out the Eurolinux desktop OS.

**Comment by AlexBaranowski** [comment]
Hi @mathewal ,

You have to disable the secure boot ATM. We have been waiting for our Secure Boot key for quite a long time. Our submission can be found at https://github.com/rhboot/shim-review/issues/258#issuecomment-1244959331. After accepting for EL 8, we planned to add support for EL9 (therefore desktop) as soon as possible. But as You can see, it's a long process that we are unable to speed up.

Unfortunately, a lot of Linux distros, especially independent ones, have this problem.

Please tell us if disabling secure boot fixed the issue.

Best,
Alex

EDIT: add @mathewal to ping about issue.

**Comment by mathewal** [comment]
Hello Alex,

Thank you for your email and the suggestion provided.

I proceeded as advised and was able to install Eurolinux 9.0 without
further issues!

👍👍👍


*Regards,Mathew Alexander*

**Comment by AlexBaranowski** [comment]
Thank You for using and reviewing EuroLinux.
