### ISSUE TITLE
man.docs.euro-linux.com

### ISSUE THREAD

**Issue by com-gas** [EuroLinux/eurolinux-distro-bugs#9]
Hi Team,

The page on mobile does not have the icon in a menu.

**Comment by com-gas** [comment]
here
![Screenshot 2023-02-28 at 15 36 30](https://user-images.githubusercontent.com/126587880/221885489-b44fa58e-fa80-4bdf-a639-14bdf30525db.png)

**Comment by AlexBaranowski** [comment]
I will look into it.

**Comment by AlexBaranowski** [comment]
Fixed.

The menu icon on the https://man.docs.euro-linux.com/ works fine. I checked it with FF Focus and Chrome on my phone.

Best,
Alex
